"""drop origin and is_synthetic from policy_documents

Revision ID: bd3cef8db66a
Revises: f7b9defd7ffa
Create Date: 2026-09-01 00:08:30.923834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3cef8db66a'
down_revision: Union[str, Sequence[str], None] = 'f7b9defd7ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_documents', 'origin')
    op.drop_column('policy_documents', 'is_synthetic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'policy_documents',
        sa.Column(
            'is_synthetic', sa.BOOLEAN(), autoincrement=False, nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        'policy_documents',
        sa.Column(
            'origin', sa.VARCHAR(), autoincrement=False, nullable=False,
            server_default='generated',
        ),
    )
    # ### end Alembic commands ###
