"""project risk_tier nullable, add aor intake fields

Revision ID: fbe0bf11bcfb
Revises: 82b954ff51eb
Create Date: 2026-09-01 17:03:50.227800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe0bf11bcfb'
down_revision: Union[str, Sequence[str], None] = '82b954ff51eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('aor_filename', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('aor_extracted_fields', sa.JSON(), nullable=True))
    op.alter_column('projects', 'risk_tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'risk_tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'aor_extracted_fields')
    op.drop_column('projects', 'aor_filename')
    # ### end Alembic commands ###
